name: Vulnerability Scanner

on:
  push:
    branches:
      - main  # Adjust based on your repository's main branch name

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap w3af sqlmap dirb masscan whatweb burpsuite dnsrecon arp-scan unicornscan nikto fierce openvas zaproxy testssl.sh knockpy dnsenum sslscan

      - name: Run Scans
        run: |
          # Command 1
          nmap -sV -O -T4 <target_IP>
          w3af -h <target_URL>
          sqlmap -u <target_URL> --dbs
          dirb <target_URL>
          masscan -p 1-65535 <target_IP>

          # Command 2
          whatweb <target_URL>
          burpsuite --scan <target_URL>
          dnsrecon -d <target_domain>
          arp-scan -I eth0 <target_IP>
          unicornscan -H <target_IP>

          # Add more commands as needed, following the format

      # You can add more steps to handle post-processing or notifications as required
